name: nLab Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release/*" ]
  schedule:
    - cron: "50 0 1,15 * *"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: ${{ matrix.runs_on }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        target_os:
          - linux
          - linux-arm64
          - macos
          - windows
        include:
          - target_os: linux
            runs_on: ubuntu-22.04
            target_architecture: x64
            executable_path: xvfb-run out/nLab-linux-x64/nLab
            artifact_path: out/make/deb/x64/nlab_*.deb
            artifact_name: 'Linux Package (deb)'
          - target_os: linux-arm64
            runs_on: ubuntu-22.04-arm
            target_architecture: arm64
            executable_path: xvfb-run out/nLab-linux-arm64/nLab
            artifact_path: out/make/deb/arm64/nlab_*.deb
            artifact_name: 'Linux Package arm64 (deb)'
          - target_os: macos
            runs_on: macos-latest
            target_architecture: universal
            executable_path: out/nLab-darwin-universal/nLab.app/Contents/MacOS/nLab
            artifact_path: 'out/make/nLab Installer.dmg'
            artifact_name: 'macOS Installer (dmg)'
          - target_os: windows
            runs_on: windows-latest
            target_architecture: x64
            executable_path: out/nLab-win32-x64/nLab.exe
            artifact_path: 'out/make/squirrel.windows/x64/*'
            artifact_name: 'Windows Installer (exe)'
    name: ${{ matrix.target_architecture }} on ${{ matrix.target_os }}
    steps:
      - name: Install Rust Toolchains
        if: matrix.target_os == 'macos'
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Install libusb
        if: startsWith(matrix.target_os, 'linux')
        run: |
          sudo apt-get update
          sudo apt-get install libusb-1.0-0-dev libudev-dev
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        # https://github.com/electron/electron/issues/42510#issuecomment-2171583086
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CODESIGN environment variable
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        run: echo "NLAB_CODESIGN=1" >> $GITHUB_ENV
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM Dependencies
        run: npm ci
      - name: Setup Digicert Keylocker
        if: matrix.target_os =='windows'
        uses: digicert/ssm-code-signing@v1.0.0
      - name: Build nLab
        run: npm run build
      - name: Setup MacOS certs
        if: matrix.target_os == 'macos'
        run: ./.github/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.MACOS_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Setup Windows certs
        if: matrix.target_os =='windows'
        run: |
          echo "${{ secrets.DIGICERT_CLIENT_CERT_FILE }}" | base64 --decode > /d/digicert_sm_cert.p12
          echo "${{ secrets.WINDOWS_SIGNING_CERT }}" | base64 --decode > /d/signing_cert.crt
      - name: Package
        run: npm run make -- --arch ${{ matrix.target_architecture }}
        env:
          DEBUG: "electron-packager,electron-windows-installer:main"
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          SM_HOST: ${{ secrets.DIGICERT_HOST }}
          SM_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE: D:\\digicert_sm_cert.p12
          CODE_SIGNING_CERT_FILE: D:\\signing_cert.crt
      - name: Smoke Test
        run: ${{ matrix.executable_path }}
        env:
          NLAB_SMOKE_TEST: 1
      - name: Archive the distributable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
      - name: Create Update Zips for macOS
        if: matrix.target_os == 'macos'
        working-directory: ./out/make/zip/darwin/universal
        run: |
          f=$(echo nLab-darwin-universal-*.zip); cp "$f" $(sed 's:universal:x64:' <<< "$f")
          f=$(echo nLab-darwin-universal-*.zip); cp "$f" $(sed 's:universal:arm64:' <<< "$f")
      - name: Archive the updaters
        if: matrix.target_os == 'macos'
        uses: actions/upload-artifact@v4
        with:
          name: macOS update packages (zip)
          path: |
            ./out/make/zip/darwin/universal/*x64*.zip
            ./out/make/zip/darwin/universal/*arm64*.zip
      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        env:
          DEBUG: "electron-packager,electron-windows-installer:main"
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          SM_HOST: ${{ secrets.DIGICERT_HOST }}
          SM_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE: D:\\digicert_sm_cert.p12
          CODE_SIGNING_CERT_FILE: D:\\signing_cert.crt
